#!/bin/sh
cat <<EOF

  _  __            _
 | |/ /  _ _ _  __| |_ _ __  __ _ __ _ _ _
 | ' < || | ' \(_-<  _| '  \/ _\` / _\` | ' \
 |_|\_\_,_|_||_/__/\__|_|_|_\__,_\__,_|_||_|
 ------------  part of Accenture Interactive

Transpiling JavaScript deliverable:
EOF

if ! [[ -d ./node_modules ]]; then
    npm install
fi

npm run test
npm run build
git add ./bin/index.js
